application: kball-test-tools
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /scripts
  static_dir: scripts

- url: /images
  static_dir: images

- url: /.*
  script: helloworld.app

libraries:
- name: webapp2
  version: "2.5.2"