application: kball-test-tools
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
# - url: /templates
#   static_dir: templates

- url: /stylesheets
  static_dir: stylesheets

- url: /scripts
  static_dir: scripts

- url: /images
  static_dir: images
  
- url: /.*
  script: helloworld.app

# To use this, I think I need to add a static folder and put images in there.
# - url: /(.*\.(gif|png|jpg))$
#   static_files: static/\1
#   upload: static/.*\.(gif|png|jpg)$

libraries:
- name: webapp2
  version: "2.5.1"
- name: jinja2
  version: "2.6"